### DISCUSSION TITLE
What's the best way to execute a command after the post download is complete?

### DISCUSSION THREAD

**Discussion by rupinderjeet** [Serene-Arc/bulk-downloader-for-reddit#714] [Q&A] [answered]
I am interested in archive-files: `json`, `xml`, `yaml`

I want to execute a command after a post is downloaded. For example:

```yaml
on_downloaded:
  json:
    command: 'chflags hidden {JSON_FILE_PATH}'
```
